packages:
  - core/*
  - e2e
  - packages/*
  - packages/providers/**/*
  - sites/*

overrides:
  "@automerge/automerge": "catalog:"
  "@automerge/automerge-repo": "catalog:"
  "@automerge/automerge-repo-keyhive": "catalog:"
  "@automerge/automerge-repo-network-messagechannel": "catalog:"
  "@automerge/automerge-repo-network-websocket": "catalog:"
  "@automerge/automerge-repo-react-hooks": "catalog:"
  "@automerge/automerge-repo-storage-indexeddb": "catalog:"
  "@automerge/automerge-subduction": "catalog:"
  "@automerge/react": "catalog:"
  "@automerge/vanillajs": "catalog:"
  "@keyhive/keyhive": "catalog:"
  solid-automerge: "catalog:"

minimumReleaseAgeExclude:
  - "@automerge/*"
  - "@inkandswitch/*"
  - "@chee/*"
  - solid-automerge

catalog:
  "@automerge/automerge": 3.3.2
  "@automerge/automerge-repo": 2.6.0-subduction.47
  "@automerge/automerge-repo-keyhive": 0.3.0-alpha.sub.8b
  "@automerge/automerge-repo-network-messagechannel": 2.6.0-subduction.47
  "@automerge/automerge-repo-network-websocket": 2.6.0-subduction.47
  "@automerge/automerge-repo-react-hooks": 2.6.0-subduction.47
  "@automerge/automerge-repo-storage-indexeddb": 2.6.0-subduction.47
  "@automerge/automerge-repo-storage-nodefs": 2.6.0-subduction.47
  "@automerge/automerge-subduction": 0.16.1
  "@automerge/react": 2.6.0-subduction.47
  "@automerge/vanillajs": 2.6.0-subduction.47
  "@codemirror/commands": ^6.10.4
  "@codemirror/language": ^6.12.4
  "@codemirror/state": ^6.7.1
  "@codemirror/view": ^6.43.6
  "@keyhive/keyhive": 0.1.0-alpha.5
  solid-automerge: ^2.0.1
  solid-js: ^1.9.13
  "@types/node": ^24.0.0
  "@types/react": 18.3.1
  "@types/react-dom": 18.3.1
  react: 18.3.1
  react-dom: 18.3.1
  typescript: ^5.9.3

allowBuilds:
  cbor-extract: true
  esbuild: true
