name: release the core packages

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: release the core
    runs-on: ubuntu-latest
    environment: Patchwork
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: check out the repository
        uses: actions/checkout@v3

      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: install javascript
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: install dependencies
        run: pnpm install

      - name: build everything
        run: pnpm build

      - name: test evything
        run: pnpm test

      - name: process changesets
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.PATCHWORK_CROW_TOKEN }}

      - name: update patchwork.inkandswitch.com
        if: steps.changesets.outputs.published == 'true'
        env:
          GH_TOKEN: ${{ secrets.PATCHWORK_CROW_TOKEN }}
        run: |
          gh api --method POST \
            repos/inkandswitch/patchwork.inkandswitch.com/dispatches \
            -f event_type=core-published

      - name: tell discord
        if: steps.changesets.outputs.published == 'true'
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.PATCHWORK_FEED_WEBHOOK_URL }}
          content: "hehe new versions of the core packages have been release"
          username: little rabbit
          avatar-url: https://em-content.zobj.net/source/animated-noto-color-emoji/427/rabbit_1f407.gif
